### ISSUE TITLE
Error at running : poetry run -m pycarla <file.mid>

### ISSUE THREAD

**Issue by dfaud** [00sapo/pycarla#4]
Hi,
I m under win10 and after installed all the dependencies, created a small runnning Carla project, running Jack.
I get this error for this syntax, launched under pycarla folder:
...\pycarla>poetry run -m pycarla k12.mid
'-m' is not recognized as an internal or external command,
operable program or batch file.

Help needed, thanks Federico

**Comment by 00sapo** [comment]
Hi, there's an error in docs apparently. You should run `poetry run python -m`, not just `poetry run -m`

**Comment by 00sapo** [comment]
Fixed by https://github.com/00sapo/pycarla/commit/f8c3f40f76aebb2ef15d71ac91d6ca4922853cc4

**Comment by 00sapo** [comment]
By the way, That section is only intended to be used for those who want to develop pycarla. If you want to just use it in your code, you are not obliged to use `poetry`
